### ISSUE TITLE
基于C++（easyx）的小游戏怎么控制帧率

### ISSUE THREAD

**Issue by evoLonation** [soft-summer-2021/summer2021#12]
类似于pygame中的FramePerSec.tick()功能，固定画面刷新的速率
（我是因为没学过python才回头打算用easyx做小游戏的T-T，结果一开始就遇到了瓶颈）

**Comment by dyn1721** [comment]
首先easyx要做双缓冲，在绘图开头用BeginBatchDraw,绘图结束用EndBatchDraw 防止出现闪屏现象
然后在循环中通过各种延时函数 如Sleep()等 控制画面更新时间
可以参考下[这个游戏的实现思路](https://zhuanlan.zhihu.com/p/24826034)
