### ISSUE TITLE
easyx中透明图片的设置

### ISSUE THREAD

**Issue by Dludora** [soft-summer-2021/summer2021#15]
在visual studio 2019中利用easyx生成图像时，使用如下函数
putimage(200, 80, &mainmenu2_0, SRCINVERT);
putimage(200, 80, &mainmenu2_1, NOTSRCERASE);
并没有生成预期的透明图像，反而生成了这样的

![Screenshot 2021-08-22 234810](https://user-images.githubusercontent.com/89232610/130361483-ccd2d2b4-2dc0-44cf-aa86-a3209f3e351f.png)
以下是彩图和掩码图
![start1_0](https://user-images.githubusercontent.com/89232610/130361489-09803ba1-08c9-4967-848c-3a3f5f0e6fb8.png)
![start1_1](https://user-images.githubusercontent.com/89232610/130361492-fb76ae01-321f-4e31-8fd9-67cd6e7d936f.png)

**Comment by dyn1721** [comment]
感觉这个应该不叫掩码图吧·· 掩码图应该是白底
 就给这两个图片想了想怎么也画不出透明效果
[参考这篇博客可以解决你的问题](https://blog.csdn.net/Qzwsdaswad/article/details/88540587)

说实话每次都这么操作很麻烦 效率也低
建议直接ps抠图解决

**Comment by dyn1721** [comment]
不会ps 可以尝试下这个免费网站 https://www.remove.bg/

**Comment by Dludora** [comment]
> 不会ps 可以尝试下这个免费网站 https://www.remove.bg/
把背景透明的图片导进去以后还是会有黑色背景

**Comment by dyn1721** [comment]
> > 不会ps 可以尝试下这个免费网站 https://www.remove.bg/
> > 把背景透明的图片导进去以后还是会有黑色背景

easyx库本身不支持透明图片直接载入
可参考[easyx官方教程](https://codebus.cn/yangw/transparent-putimage)的方法4 
最后效果：
![image](https://user-images.githubusercontent.com/49605687/130384412-b174e72e-c42c-4fc2-9d24-9924ed04bbb9.png)
