### ISSUE TITLE
pygame中一队的对象出现 数据显示矩形是移动的但是图片只有一张

### ISSUE THREAD

**Issue by Mr-alsocrazy** [soft-summer-2021/summer2021#16]
https://bhpan.buaa.edu.cn:443/link/59E551894CABF365545CC6E96E777BA0
有效期限：2021-09-21 23:59
文件已上传 包括自己写的和使用的图片

**Comment by dyn1721** [comment]
这种问题建议自己通过[断点调试](https://blog.csdn.net/chenggong2dm/article/details/9368641)解决，不能指望直接扔上来个项目文件让助教们帮你们de所有bug 毕竟还是自己开发项目  

如果实在解决不了，请详细说明。描述问题详细一些，把自己的需求、自己为这个需求写的代码、以及遇到的问题说清楚。

**Comment by Mr-alsocrazy** [comment]
好的 感谢
