### ISSUE TITLE
easyx中rotateimage函数在清屏后仍会显示原图像

### ISSUE THREAD

**Issue by Fengbujue862** [soft-summer-2021/summer2021#20]
![tkerror](https://user-images.githubusercontent.com/89260727/130430269-fc330184-9f60-416c-99ae-3170e867ca42.PNG)
另外使用白色图片旋转会有灰色出现
![TKERROR3](https://user-images.githubusercontent.com/89260727/130430551-86783030-e32a-43d8-a90f-9f7fa0aabb7e.PNG)

**Comment by dyn1721** [comment]
原图像是什么 相关代码发一下？

**Comment by Fengbujue862** [comment]
> 原图像是什么 相关代码发一下？
原图像意识是未旋转的图像
if (GetAsyncKeyState(VK_LEFT)) {
		    rotateimage(&img, &tk1, 0, WHITE);
			rotateimage(&tk1, &img, PI / 1000, WHITE);
}
这个代码后会到循环开头clear后再输出图像
不应该还有原本图像😐

**Comment by Fengbujue862** [comment]
> 原图像是什么 相关代码发一下？
原图像意识是未旋转的图像
if (GetAsyncKeyState(VK_LEFT)) {
		    rotateimage(&img, &tk1, 0, WHITE);
			rotateimage(&tk1, &img, PI / 1000, WHITE);
}
这个代码后会到循环开头clear后再输出图像
不应该还有原本图像😐

**Comment by dyn1721** [comment]
完整代码发一下？

**Comment by Fengbujue862** [comment]
> 完整代码发一下？

[tk.txt](https://github.com/soft-summer-2021/summer2021/files/7031227/tk.txt)

**Comment by dyn1721** [comment]
略做修改 代码如下 可以正常旋转了

思路就是避免一直使用easyx库的旋转函数去旋转图片

我的做法是保存一个旋转角度变量，每次改变这个变量然后再旋转原图

原因目前我还没找到，应该是这个函数自身的问题吧（） 

```
#include<stdio.h>
#include<graphics.h>
#include<easyx.h>
#include<mmsystem.h> 
#include<math.h>
#include<conio.h>//getch
#include <windows.h> 
#pragma comment(lib,"winmm.lib")
#define PI 3.14159265359

int main() {
	initgraph(640, 480, EW_SHOWCONSOLE);//窗口大小
	double x = 0, y = 0, i = 0;
	double angle = 0;
	IMAGE img, zhe, tk1;
	//BGM();
	loadimage(&tk1, "./1.jpg", 200, 200);
	loadimage(&img, "./1.jpg", 200, 200);
	putimage(x, y, &tk1);
	while (1) {
		BeginBatchDraw();
		setbkcolor(WHITE);
		cleardevice();
		if (GetAsyncKeyState(VK_LEFT)) {
			angle += PI / 1000;
		}
		rotateimage(&img, &tk1, angle, WHITE);
		putimage(x, y, &img);
		FlushBatchDraw();
		
	}
	closegraph();//关闭窗口
	return 0;
}
```

**Comment by Fengbujue862** [comment]
谢谢学长
