### ISSUE TITLE
pygame函数库

### ISSUE THREAD

**Issue by Ten-Mao** [soft-summer-2021/summer2021#21]
请问哪里有pygame所有函数的列举，用样例以及参数说明

**Comment by dyn1721** [comment]
这种一般在[官方文档](https://www.pygame.org/docs/) 最详细最准确
有个大大个人翻译了下 [中文官方文档](https://blog.csdn.net/Enderman_xiaohei/article/details/87708373)

其他同学有好用的资源也可以补充哈~
