### ISSUE TITLE
pygame 写出来的程序打开之后点击右上角'x'发现关不掉怎么办？

### ISSUE THREAD

**Issue by Mr-alsocrazy** [soft-summer-2021/summer2021#22]
点击x 关不掉，设置q键退出关不掉 只能在任务管理器结束进程

**Comment by dyn1721** [comment]
发下代码？

**Comment by Mr-alsocrazy** [comment]
压缩文件可以吗 用北航盘传

**Comment by Mr-alsocrazy** [comment]
https://bhpan.buaa.edu.cn:443/link/CA9C9FC4FFA62CC93660AEEEC9ABDAEA
有效期限：2021-09-21 23:59
另外还想问一下，怎么查看图片上像素的坐标...

**Comment by dyn1721** [comment]
debug发现问题主要出在主函数33行 你在**另一个文件**中使用了pygame的**event** 

将这一句注释掉就可以正常退出

建议把**event事件相关处理的函数都放到主函数下**，并且pygame.event.get()遍历只能出现一次 

原因就是下图官方文档解释：

![T 7@3XQ0AYL`6 (@)1I1RX](https://user-images.githubusercontent.com/49605687/130461397-860960d5-57e1-4de2-93eb-14d9383eca0e.png)

**Comment by Mr-alsocrazy** [comment]
换到里面还是不太行...是一次循环只能用一次event？

**Comment by Mr-alsocrazy** [comment]
已解决
