### ISSUE TITLE
每次发射子弹的时候发射着发射着就退出去了，也不太明白

### ISSUE THREAD

**Issue by fenghora** [soft-summer-2021/summer2021#27]
https://bhpan.buaa.edu.cn:443/link/3A50429FD35B318BFD605DE97FD265F2
![微信图片_20210823230421](https://user-images.githubusercontent.com/89394447/130473375-f042b752-77f4-4a96-99b4-cfa165c09884.jpg)

**Comment by fenghora** [comment]
https://bhpan.buaa.edu.cn:443/link/A61D6831A1AA803DF12E2020BF664BE1
出错的函数稍微变了一下
![微信图片_20210824204515](https://user-images.githubusercontent.com/89394447/130618555-22624ec3-8ab8-4a47-a771-063470032cb5.jpg)

**Comment by hzy1721** [comment]
一颗子弹击中多个敌机，每个敌机都需要 reset，但是这颗子弹只需要 remove 一次。而且最好不要在 for 循环过程中删除元素。

```python
def hit(self):
    global score, bullets, enemies
    hit_enemy = False
    for e in enemies:
        if distance(self.x, self.y, e.x, e.y) < 30:
            # 击中目标
            bao_sound.play()
            e.reset()
            score += 10
            hit_enemy = True
    return hit_enemy
```

```python
def show_bullets():
    for b in bullets.copy():
        screen.blit(b.img, (b.x, b.y))
        if b.hit():
            bullets.remove(b)
        else:
            b.y -= b.step
            if b.y <= 0:
                bullets.remove(b)
```
