### ISSUE TITLE
如何查看图片上面的像素点的坐标？

### ISSUE THREAD

**Issue by Mr-alsocrazy** [soft-summer-2021/summer2021#29]

**Comment by hzy1721** [comment]
查看鼠标所在位置像素点的坐标吗？

**Comment by Mr-alsocrazy** [comment]
嗯对

**Comment by KarryBanana** [comment]
如果我没理解错问题的意思的话 ）
你可以右键想查看的图片——打开方式——画图

![dayi](https://user-images.githubusercontent.com/25265710/130550529-4eafe37c-5c1c-49d5-8b6f-07b6e0b47b82.png)


鼠标在图片上移动，对应位置的像素点位置会显示在左下角

**Comment by hzy1721** [comment]
如果是 pygame，用 `pygame.mouse.get_pos()`。
