### ISSUE TITLE
easyx使用遮罩图但是背景有空白区域出现

### ISSUE THREAD

**Issue by Fengbujue862** [soft-summer-2021/summer2021#34]
![error1](https://user-images.githubusercontent.com/89260727/130575453-679f5123-83c6-44dc-81db-8042b9327945.PNG)
下面是原图和遮罩图
![tkone](https://user-images.githubusercontent.com/89260727/130575478-0379d3e1-828a-4c36-ba3d-100e69691e3e.jpg)
![tkzhe1](https://user-images.githubusercontent.com/89260727/130575493-3d8d20a1-cb6b-4e31-806f-27306048f60c.jpg)

**Comment by dyn1721** [comment]
重复问题 参考#15
