### ISSUE TITLE
EasyX图像编程中鼠标操作问题

### ISSUE THREAD

**Issue by nevergyt** [soft-summer-2021/summer2021#35]
鼠标点击第二第三区域无反应，无法转到相应的函数
![屏幕截图 2021-08-24 202113](https://user-images.githubusercontent.com/89232835/130615542-8ed9530b-93c2-4143-b07c-2724b44a4da9.png)

**Comment by huyikun** [comment]
建议输出 button_mode.x  button_mode.y 的值自行调试
以及对于button_mode.x的判断可以只写一个if 减少代码重复
