### ISSUE TITLE
pygame实现跳跃功能时为什么会偶尔出现不能下落，一直向上移动的情况呢？

### ISSUE THREAD

**Issue by AboveParadise** [soft-summer-2021/summer2021#38]
![图片](https://user-images.githubusercontent.com/89033914/130729150-61b29a2d-3ab6-499a-b11f-e69f8b6c5c78.png)
![图片](https://user-images.githubusercontent.com/89033914/130729222-b201c6ed-cbed-433f-be97-d12e9ac1139e.png)
![图片](https://user-images.githubusercontent.com/89033914/130729242-75ed0e01-f63a-471e-955c-fd6cedf3c06b.png)
我怀疑是与time那块有关

**Comment by hzy1721** [comment]
可以自己 print 调试一下，找一下什么情况会一直向上。根据你发的截图我看不太懂逻辑是什么。
