### ISSUE TITLE
mac系统安装Android Studio，手动安装并配置gradle后仍然报错

### ISSUE THREAD

**Issue by VeraMayLin** [soft-summer-2021/summer2021#39]
在mac系统安装Android  Studio后，手动安装并配置了gradle后仍然出现这样的报错应该怎么解决<img width="1440" alt="image" src="https://user-images.githubusercontent.com/82801068/130736945-81f924ef-3ec5-459b-9fd3-cb121dc577c6.png">

**Comment by hzy1721** [comment]
不需要手动安装 gradle。把 VPN 打开，打开项目后 AS 会自动下载需要版本的 gradle 和其他依赖。

**Comment by hzy1721** [comment]
- [https://blog.csdn.net/fenggering/article/details/95678340](https://blog.csdn.net/fenggering/article/details/95678340)
- [https://blog.csdn.net/weixin_46218781/article/details/104911908](https://blog.csdn.net/weixin_46218781/article/details/104911908)
- [https://stackoverflow.com/questions/51218535/unable-to-resolve-dependency-for-appdebug-compileclasspath-could-not-resolv](https://stackoverflow.com/questions/51218535/unable-to-resolve-dependency-for-appdebug-compileclasspath-could-not-resolv)
- [https://cloud.tencent.com/developer/article/1592801](https://cloud.tencent.com/developer/article/1592801)

在安卓开发中这种环境问题还挺常见的，最简单的解决方法就是确保网络通畅 (能够访问外网，因为涉及到 Google 的一些东西)，从[官网](https://developer.android.google.cn/) 下载安装 Android Studio，然后 AS 会自动下载和安装需要的各种依赖。

并且不要使用太老的库，比如上面截图里的 android.support，minSdkVersion 也不要太低 (使用网上的老项目可能有这些问题，用 AS 新建项目并使用默认配置不会有这些问题，会自动使用 androidx)。

**Comment by VeraMayLin** [comment]
开VPN下载仍然无法解决，按照博客里的方法尝试过了也不行

**Comment by hzy1721** [comment]
请问是从官网下载 AS，然后新建一个项目，编译运行就出现这样的错误吗？

我也没碰到过这种问题，只能排除可能出问题的步骤。

**Comment by VeraMayLin** [comment]
是安装的时候尝试新建项目，打开之后就会这样，不是编译运行的时候

**Comment by hzy1721** [comment]
（VPN 一直开着）

重新安装一下？记得先卸载

[https://developer.android.google.cn/studio](https://developer.android.google.cn/studio)

<img width="639" alt="截屏2021-08-25 下午5 12 32" src="https://user-images.githubusercontent.com/48407687/130763242-1613d6b4-c873-4454-b112-99b908c5eca7.png">

新建项目的时候尽可能不要用旧的库：

<img width="1012" alt="截屏2021-08-25 下午5 10 43" src="https://user-images.githubusercontent.com/48407687/130763280-6f9cf156-2130-4c59-be3f-6ec54406dc82.png">

**Comment by VeraMayLin** [comment]
重装时打开VPN仍然无法自动下载gradle7.0.2

**Comment by hzy1721** [comment]
可以尝试给 gradle 换源，用阿里云镜像。

[https://developer.aliyun.com/mirror/maven](https://developer.aliyun.com/mirror/maven)

[https://www.cnblogs.com/huiyi0521/p/10997152.html](https://www.cnblogs.com/huiyi0521/p/10997152.html)

**Comment by VeraMayLin** [comment]
感谢学长，问题解决了
