### ISSUE TITLE
wpf如何添加控件？

### ISSUE THREAD

**Issue by woarthur** [soft-summer-2021/summer2021#4]
![图片](https://user-images.githubusercontent.com/78649056/130323103-e3146d6e-51c1-491c-9181-02656c9cc9db.png)
如图所示，请问什么叫在控件中添加MouseDragElementBehavior，具体该如何操作呢，谢谢~

**Comment by huyikun** [comment]
Image就是一个控件呀 你所说的不就是图中代码段的部分吗
