### ISSUE TITLE
如何实时监视手机应用的使用时间，并实现在到达预定时间时关闭该应用？

### ISSUE THREAD

**Issue by orz010** [soft-summer-2021/summer2021#41]
CSDN上找了好多资料都没有找到合适的方法

**Comment by hzy1721** [comment]
普通应用不能获取这么高的权限吧，而且也有侵犯隐私的嫌疑，系统不太可能开放这种 API。是 “时间锁” 那个应用吗，我觉得大概率不行。

**Comment by havesomecolo** [comment]
不行就周期性查找进程，将pid和app name匹配，得到在前台以及后台的是哪些app

**Comment by havesomecolo** [comment]
https://blog.csdn.net/github_37271067/article/details/85292543
csdn上不是有的吗
