### ISSUE TITLE
QT使用三元表达式导致调试中途图退出，以及调试到中途执行语句的标记不见了是为什么

### ISSUE THREAD

**Issue by luoyashuo** [soft-summer-2021/summer2021#42]
在QT中编写了这样一段代码：
 boardState::GoTurn who=(this->curTurn==boardState::GO_TURN_WHITE?boardState::GO_TURN_BLACK:boardState::GO_TURN_WHITE);//这里要记录的是上一步是谁下的
![1](https://user-images.githubusercontent.com/83280347/130754061-57b3cca2-853c-4198-ad1d-2a1ae6a02a44.jpg)
![1 - 副本](https://user-images.githubusercontent.com/83280347/130754063-ec5351d3-0c1e-4173-95d0-e47aabf880ee.jpg)
![1 - 副本 (2)](https://user-images.githubusercontent.com/83280347/130754062-15149071-ce73-409d-931d-5531a03ccd95.jpg)
然后进行调试的时候每次到这里，哪个表示执行到哪一步的小箭头消失了，然后只能终止调试，如果不用三元表达式就可以继续调试了，想知道是什么原因，是不是三元表达式用得不对？

**Comment by luoyashuo** [comment]
![图片](https://user-images.githubusercontent.com/83280347/130755591-ee8ff6b8-6bf8-4629-bde2-27351775a183.png)
好像一走到这条赋值语句调试的小箭头就没了，为什么啊？

**Comment by hzy1721** [comment]
我也没用过 Qt Creator，不过我觉得你可以先用 printf/cout 调试法来解决 bug，效率也挺高的。
