### ISSUE TITLE
tkinter在按钮的回调函数中贴图片无法显示

### ISSUE THREAD

**Issue by WhySoHardToGiveName** [soft-summer-2021/summer2021#43]
![A(SK0{`S2563ELJ `D Z1{3](https://user-images.githubusercontent.com/89514061/130758278-004fb4f3-c65f-4c92-9b82-f58df63e82dd.png)
我搞了个按钮可以让用户选择一张照片，然后想在window中把照片显示出来，但是运行之后显示出来是空白的
![$4W}9KRME1OE8102QZNQ TW](https://user-images.githubusercontent.com/89514061/130758582-a9a40fba-a2e8-450d-9a10-9d71c966039a.png)
放到主函数里是可以显示出来的，但放到按钮的回调函数里就显示不了

**Comment by KarryBanana** [comment]
可以看下下面这两篇博客能不能帮你解决问题
[博客1 关于Python tkinter中出现的坑（界面Tk()+图片显示）](https://blog.csdn.net/weixin_43328749/article/details/88247103?utm_medium=distribute.pc_relevant.none-task-blog-2%7Edefault%7EBlogCommendFromMachineLearnPai2%7Edefault-3.essearch_pc_relevant&depth_1-utm_source=distribute.pc_relevant.none-task-blog-2%7Edefault%7EBlogCommendFromMachineLearnPai2%7Edefault-3.essearch_pc_relevant)
[博客2 关于tkinter在函数中无法显示图片](https://blog.csdn.net/qq_37087170/article/details/109329327)

**Comment by WhySoHardToGiveName** [comment]
> 可以看下下面这两篇博客能不能帮你解决问题
> [博客1 关于Python tkinter中出现的坑（界面Tk()+图片显示）](https://blog.csdn.net/weixin_43328749/article/details/88247103?utm_medium=distribute.pc_relevant.none-task-blog-2%7Edefault%7EBlogCommendFromMachineLearnPai2%7Edefault-3.essearch_pc_relevant&depth_1-utm_source=distribute.pc_relevant.none-task-blog-2%7Edefault%7EBlogCommendFromMachineLearnPai2%7Edefault-3.essearch_pc_relevant)
> [博客2 关于tkinter在函数中无法显示图片](https://blog.csdn.net/qq_37087170/article/details/109329327)

解决了 感谢！
