### ISSUE TITLE
pygame.font.render如何设置透明背景？

### ISSUE THREAD

**Issue by Mr-alsocrazy** [soft-summer-2021/summer2021#44]

**Comment by hzy1721** [comment]
[https://www.pygame.org/docs/ref/font.html#pygame.font.Font.render](https://www.pygame.org/docs/ref/font.html#pygame.font.Font.render)

<img width="546" alt="截屏2021-08-25 下午6 45 21" src="https://user-images.githubusercontent.com/48407687/130777230-939e75b6-1f39-48a3-9b3d-d3ecfdcf206b.png">
