### ISSUE TITLE
wpf拖动生成标签

### ISSUE THREAD

**Issue by Chaoticsteven** [soft-summer-2021/summer2021#45]
![bd113bb0ed594890340f65125ae856e](https://user-images.githubusercontent.com/77388522/130766258-beed19a0-5270-49fd-9e9c-9fe3fcaba088.jpg)
想让每行能够拖动生成 一个标签，同时获取标签头尾对应时间标尺信息，标签需要能点击展开另一个界面，应该用什么控件或控件组来实现。

**Comment by dyn1721** [comment]
sry 可能助教们对wpf都不太熟悉
