### ISSUE TITLE
tkinter中按钮使用的回调函数能否取回返回值？

### ISSUE THREAD

**Issue by WhySoHardToGiveName** [soft-summer-2021/summer2021#47]
![76decc7c1f69abce95d91d399c5b35d](https://user-images.githubusercontent.com/89514061/130805556-de411552-c275-4dc7-951a-f342a2fc1651.png)
![image](https://user-images.githubusercontent.com/89514061/130805633-80e59571-1341-4479-90bf-75a515ddebfc.png)

想用按钮选一张图片之后搞到图片的地址，方便后面处理，但不知道回调函数怎么取回返回值
搜到一篇csdn，但好复杂看不太懂。。
https://blog.csdn.net/Cengineering/article/details/111280136?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522162989484816780366559283%2522%252C%2522scm%2522%253A%252220140713.130102334.pc%255Fall.%2522%257D&request_id=162989484816780366559283&biz_id=0&utm_medium=distribute.pc_search_result.none-task-blog-2~all~first_rank_ecpm_v1~rank_v29_ecpm-4-111280136.pc_search_result_control_group&utm_term=tkinter%E5%9B%9E%E8%B0%83%E5%87%BD%E6%95%B0%E8%BF%94%E5%9B%9E%E5%80%BC&spm=1018.2226.3001.4187
或者有没有什么别的解决思路？

**Comment by WhySoHardToGiveName** [comment]
发issue的时候怎么添加label啊…？

**Comment by dyn1721** [comment]
无法直接获得回调函数的返回值，因为回调函数只有点击按钮等**触发command行为发生才会执行** 
所以这个csdn的大致思路应该就是构造一个类 回调函数写成类的方法 然后执行时将文件名保存成类的属性
没咋用过tkinter 这篇博客我也没太看明白（ 
所以我按照我的想法简单写了个demo 基本可以实现你需要的获取文件地址的需求

```
import tkinter as tk
from tkinter.filedialog import *

class dataCenter():
    def __init__(self):
        self.flie=''

    def selectFile(self):
        filepath = askopenfilename()  # 选择打开什么文件，返回文件名
        filename.set(filepath)  # 设置变量filename的值
        self.flie=filepath

    def printFile(self):
        print(self.flie)
        return self.flie

root = tk.Tk()
filename = tk.StringVar()
outputpath = tk.StringVar()
filenewname = tk.StringVar()
data=dataCenter()

tk.Label(root, text='选择文件').grid(row=1, column=0, padx=5, pady=5)
tk.Entry(root, textvariable=filename).grid(row=1, column=1, padx=5, pady=5)
tk.Button(root, text='打开文件', command=data.selectFile).grid(row=1, column=2, padx=5, pady=5)
tk.Button(root, text='输出文件名', command=data.printFile).grid(row=1, column=4, padx=5, pady=5)
root.mainloop()
```
