### ISSUE TITLE
pygame精灵的update（）函数如何修改所需参数个数？

### ISSUE THREAD

**Issue by AboveParadise** [soft-summer-2021/summer2021#48]
![图片](https://user-images.githubusercontent.com/89033914/130896195-49ccacf9-77bc-4520-8423-cae0b7fb775c.png)
![图片](https://user-images.githubusercontent.com/89033914/130896305-7a9962cc-b24a-4ab5-8d5d-581722713778.png)
pedal_group是一个精灵组，其中精灵的update方法如图2所示，为什么图1调用精灵组update时我传入一个参数他会报错呢？

**Comment by dyn1721** [comment]
发下文件吧 目前看着感觉没啥问题

**Comment by AboveParadise** [comment]
> 
> 
> 发下文件吧 目前看着感觉没啥问题

> 
[pedal_sprite.docx](https://github.com/soft-summer-2021/summer2021/files/7051643/pedal_sprite.docx)
[main.docx](https://github.com/soft-summer-2021/summer2021/files/7051644/main.docx)
（好像发不了py文件emmm）

**Comment by dyn1721** [comment]
是不是缺了个doodler_sprite 也发下？

**Comment by dyn1721** [comment]
排查了下 你这个pedal_group不仅存着Regpedal精灵（就是你图二正确声明参数个数的类）而且还有MovingPedal可移动踏板精灵

问题就出现在这第二种 你的update声明还是**def update(self)：**

所以当精灵组update时将你传入参数一个个给每个组内精灵并且调用他们的update方法时

第二种踏板就会多出一个参数报错

关于精灵组update机制 参考官方文档：

![image](https://user-images.githubusercontent.com/49605687/130925180-24cb3ffc-eaad-40c5-8991-0cfd166425b9.png)


我试了下将MovingPedal多传一个参数后实测你的游戏就可以正常运行了

ps：游戏做的不错！看起来效果很好 继续加油
