### ISSUE TITLE
VS2019 插入音乐无法播放的问题

### ISSUE THREAD

**Issue by ZhMX1** [soft-summer-2021/summer2021#49]
#include <iostream>
#include <mmsystem.h>
#pragma comment(lib,"winmm.lib")
using namespace std;
头文件运用如上
int main(){
mciSendString(_TEXT("open A.mp3 alias music"), 0, 0, 0);
 int x=mciSendString(_TEXT("play A.mp3"), 0, 0, 0);//A.mp3是放在对应目录底下的一个音频文件
 cout << x << endl;//报错277，如果正确打开返回0并放歌
 while (1) {}
}
想请问助教这是为什么，在别人的程序上可以正确运行，我的无法运行，错误代码277且无声

**Comment by dyn1721** [comment]
报错了是吗 截图一下报错内容？

**Comment by ZhMX1** [comment]
已经解决了，好像是音频来源的问题？网易云的音频不行酷狗的可以了，谢谢助教
