### ISSUE TITLE
png格式的图在ps中看背景透明，放在python运行程序中背景为黑色如何解决？

### ISSUE THREAD

**Issue by AboveParadise** [soft-summer-2021/summer2021#5]

**Comment by hzy1721** [comment]
能放一下相关的代码和截图吗

**Comment by AboveParadise** [comment]
> 
> 
> 能放一下相关的代码和截图吗

![图片](https://user-images.githubusercontent.com/89033914/130339519-dcbc243b-40ae-4854-9a85-5ba7081c8b71.png)
![图片](https://user-images.githubusercontent.com/89033914/130339528-27bda25e-651a-43a4-aa98-36d8f83176ea.png)
![图片](https://user-images.githubusercontent.com/89033914/130339531-2a99cf24-669d-4cb5-b80c-b487a31978ab.png)
![图片](https://user-images.githubusercontent.com/89033914/130339533-835b892f-4cd4-4fb3-ade6-ffb2d198b450.png)

**Comment by hzy1721** [comment]
把 `convert()` 改成 `convert_alpha()`
