### ISSUE TITLE
将Eclipse中项目打包为jar（内含文本文件）

### ISSUE THREAD

**Issue by Rnkind** [soft-summer-2021/summer2021#50]
如题，项目里的文本文件是用于向用户说明的一些文字信息，存在下图所示的text文件夹里面
![1IZWA58YAV 8Q4UO}}TW4I9](https://user-images.githubusercontent.com/89282985/130910735-26e1d328-b202-4b0e-b807-030d667d3a9a.png)
现在用Eclipse的工具试了一下导出，成功导出了可执行jar文件，但没有把text文件也导入进去
请问助教如何解决找不到文件的问题？

**Comment by havesomecolo** [comment]
https://www.cnblogs.com/huang-bin/p/5833528.html
是不是可以这样解决

**Comment by Rnkind** [comment]
这个跟Android的机制不太一样吧
Eclipse中自己的Resource应该如何设置？

**Comment by Rnkind** [comment]
其实也可以最后完全做完以后把jar文件跟资源文件夹放到同一个目录下，
这样最后可以算成品吗？
（抱歉还不太会反射机制，只能先这么实现了

**Comment by KarryBanana** [comment]
可能不是text文件没有导入进去，打包成jar包后读取文件的方式要做一定的改动，例如原来用相对路径的方式读取text文件，在jar包里就是不可行的了
可以利用`this.getClass().getResourceAsStream`以流形式读取jar包中的内容

> [参考博客](https://blog.csdn.net/u013467442/article/details/88807557)
