### ISSUE TITLE
easyx中子弹与墙壁的判定时准时不准

### ISSUE THREAD

**Issue by Fengbujue862** [soft-summer-2021/summer2021#51]
（判定条件在测试时1，2，3，4都同时使用过）
![error](https://user-images.githubusercontent.com/89260727/130911039-e6c55fd4-2a7f-4f54-99f2-eb3bd02ddd87.PNG)
![error1](https://user-images.githubusercontent.com/89260727/130911046-f7a8ab92-ccfa-49f4-81e8-0dc0107fb8a2.PNG)
![error3](https://user-images.githubusercontent.com/89260727/130911051-68d06076-0371-4cec-a2c8-12b6d37bbbbd.PNG)

**Comment by dyn1721** [comment]
自己断点debug或者print控制台输出试试？ 就目前几个图我也看不太明白啥意思，也不太清楚你命名的具体每个变量含义

**Comment by dyn1721** [comment]
实在无法解决请发送完整项目压缩包 。可能需要我自己电脑跑一下效果和进一步排查问题

**Comment by Fengbujue862** [comment]
> 实在无法解决请发送完整项目压缩包 。可能需要我自己电脑跑一下效果和进一步排查问题

地图中的墙壁之前是全部用1来表示的可以正常的运行但有时对于反弹方向的判断有问题，之后为了方便判断方向就将竖直墙壁用2来标识，但是修改后就无法正常运行了，输出数据已经超出原有的屏幕范围了

**Comment by dyn1721** [comment]
就这个报错来看 极有可能是数组越界  print检查一下吧

**Comment by Fengbujue862** [comment]
边界问题多加了一个判断已经解决了 但是chackwall墙壁的判断还是不行

**Comment by Fengbujue862** [comment]
> 就这个报错来看 极有可能是数组越界 print检查一下吧

![error4](https://user-images.githubusercontent.com/89260727/130937751-4d066aa5-e708-40c4-b842-bea2c1b1630d.PNG)
这是结构体的具体内容

**Comment by dyn1721** [comment]
自己调试看看吧 [断点调试](https://zhuanlan.zhihu.com/p/295372998)  这些问题基本都是某处代码或者变量细节的问题。
 助教也很难直接看出问题在哪  
在断点调试中看哪一步的变量值和你想实现的有差错
