### ISSUE TITLE
在游戏中按键，屏幕左上角出现的字母怎么解决

### ISSUE THREAD

**Issue by oldGreenIsMe** [soft-summer-2021/summer2021#53]
如题，怎么才能避免出现这些字母，让界面更加美观
![image](https://user-images.githubusercontent.com/89284131/130921056-3b1415e2-5a37-47f9-8bdc-6ffe7ba2391e.png)

**Comment by dyn1721** [comment]
额 这个问题我感觉不需要咱来解决 用户切个输入法就好
市面很多游戏 你要是中文输入法按aswd也都会弹出这个输入框 
可能游戏开发者都觉得这个不属于自己的问题吧

**Comment by oldGreenIsMe** [comment]
> 额 这个问题我感觉不需要咱来解决 用户切个输入法就好
> 市面很多游戏 你要是中文输入法按aswd也都会弹出这个输入框
> 可能游戏开发者都觉得这个不属于自己的问题吧

好的谢谢啦
