### ISSUE TITLE
请老师、助教提一些修改建议，非常感激！

### ISSUE THREAD

**Issue by Risveglio136** [soft-summer-2021/summer2021#54]
https://bhpan.buaa.edu.cn:443/#/link/827318E44CE85F57ABB995272CA75FE7

**Comment by dyn1721** [comment]
哇 目前能达到这个完成度已经非常不错了！
这应该就是一个类似贴吧的可以发帖聊天的小程序吧？
我提一下我的一些建议哈：
1. 我感觉这个铭牌没必要当做帖子的标题 毕竟可能用户以为这一串数字只是乱码 可以当做隐藏的属性 同时显示标题 大家可以更快速了解这个帖子在聊什么主题
2. 所有帖子都在主页更新，如果时间够可以尝试开发一下圈子？类似贴吧每个不同吧 豆瓣每个不同小组一样 这样大家更能找到一起聊天的人
3. 这个可能麻烦点 用户可不可以发图片或者emoji？
4. 用户个人资料感觉可以更详细点 比如签名呀 兴趣爱好呀 方便别的用户了解自己
5. UI优化等美观小问题

总之，你的作品非常不错，很有申优的潜力 ，但功能感觉还是略少，毕竟还有不少时间嘛 尝试再升级迭代下？加油！

**Comment by Risveglio136** [comment]
谢谢建议❤，不过这个小程序性质还是和贴吧不太一样的，因为是树洞嘛，不能带有身份特征，所以没有设置个人资料。
图片和emoji我试试，应该可以加上去的
铭牌的话我是参考的清华树洞QWQ，它们就是这样的随机六位数，感觉可以体现用户的一个标识
圈子这个我也想过，但不太好实现，我再尝试一下吧@~@

**Comment by KarryBanana** [comment]
作品完成度挺高的，还有些细节可以再继续优化一下！
我的一些个人建议hhh
1、铭牌换成标签可能更好一点，一串数字用户可能无法理解铭牌的含义，标签可以参考github issue标签的形式
2、帖子底部可以考虑加上点赞数和收藏数，页面显得更加饱满一些
![image](https://user-images.githubusercontent.com/25265710/130946074-e0c1e0f4-e157-4526-a4ef-64dda0408d87.png)

整体功能上的小细节处理的都还挺好的，继续完善吧，加油！

**Comment by dyn1721** [comment]
> 谢谢建议❤，不过这个小程序性质还是和贴吧不太一样的，因为是树洞嘛，不能带有身份特征，所以没有设置个人资料。
> 图片和emoji我试试，应该可以加上去的
> 铭牌的话我是参考的清华树洞QWQ，它们就是这样的随机六位数，感觉可以体现用户的一个标识
> 圈子这个我也想过，但不太好实现，我再尝试一下吧@~@

嗯嗯 很不错的想法 是我理解错了哈 
继续加油吧 记得到时候用户文档啥的写清楚哈
