### ISSUE TITLE
tkinter如何保存图片到本地

### ISSUE THREAD

**Issue by WhySoHardToGiveName** [soft-summer-2021/summer2021#55]
![image](https://user-images.githubusercontent.com/89514061/130935288-edb790ee-f611-4674-93c4-8a83fb61a9b9.png)
![image](https://user-images.githubusercontent.com/89514061/130935473-f4ed32fb-4950-4f8c-a017-0bbd107aa895.png)
经过处理后得到img_panda_result的图片，希望能让用户把图片保存到本地，但用asksaveasfilename函数保存后看不到保存的图片
![image](https://user-images.githubusercontent.com/89514061/130935855-1275ccd5-c7bf-4bcd-9580-ff8c7459e4e8.png)
有没有什么解决办法？

**Comment by dyn1721** [comment]
`asksaveasfilename`函数作用是选择以什么文件名保存，返回保存路径 本身不会保存图片
我看你用到了opencv
通过`asksaveasfilename`获取用户希望保存本地的path后再用opencv的保存图像函数
`cv.imwrite(savepath, img)`
