### ISSUE TITLE
pyinstaller打包完后的.exe黑屏出现一段文字后立即闪退如何解决？

### ISSUE THREAD

**Issue by Ten-Mao** [soft-summer-2021/summer2021#56]

**Comment by dyn1721** [comment]
是报错了吗 出现的文字是报错信息？

**Comment by KarryBanana** [comment]
有报错信息嘛？有的话可以直接查对应的报错信息

**Comment by dyn1721** [comment]
这个pyinstaller啊 去年也是打包各种问题不断 而且原因多种多样。
我总结了下去年涉及的几种原因，可以逐一排查下（这些要都不是我也没招了）：
1.**首先确认IDE里工程运行没问题**
2.部分**三方库不支持** 请详细查阅[官方wiki](https://github.com/pyinstaller/pyinstaller/wiki/Supported-Packages) 有介绍
3.**[字体问题](https://blog.csdn.net/D_ingjie/article/details/104391076)** 
4.**[音乐格式问题](https://ask.csdn.net/questions/1051437)** 据说不支持mp3
5.**图片资源**路径错了 /未找到
6.pyinstaller 打包后 **[os路径获取不正确](https://blog.csdn.net/qq_41817302/article/details/88684703)**

如果以上方面都试过不行，通过各种**搜索引擎**搜索**报错信息**查找解决方案

**Comment by Ten-Mao** [comment]
好的我试试

**Comment by Ten-Mao** [comment]
已经解决了，是字体问题。另外刚才在尝试的过程发现pygame好像无法识别wav格式，在pycharm里面也报错，改回MP3格式后才能够正常运行

**Comment by Ten-Mao** [comment]
谢谢助教
