### ISSUE TITLE
用vs写控制台程序时，如何把图片放到想要的位置

### ISSUE THREAD

**Issue by theignorantt** [soft-summer-2021/summer2021#59]
如题，除了用putimage函数加坐标外，能否直接把图片放在窗口想要的位置，或者有什么方法能得到该位置坐标也行，而不是一次一次调坐标到想要的位置

**Comment by dyn1721** [comment]
直接拖动图片到想要位置只用easyx是实现不了的。easyx上手简单的原因就是它真的很简单，功能少。

你是想要获取对应点位置？这也挺简单的，**QQ截图**就可以量取像素距离，还可以**拾取色号**，不用一次次代码运行测量像素位置

**Comment by theignorantt** [comment]
谢谢助教老师的帮助
