### ISSUE TITLE
在安卓项目中启动另一个activity失败并在终端中返回Attempt to invoke virtual method on a null object reference

### ISSUE THREAD

**Issue by MOYFbeta** [soft-summer-2021/summer2021#6]
[Uploading test.zip…]()
zip中是整个项目

源代码基本是抄写安卓开发者文档https://developer.android.google.cn/training/basics/firstapp/starting-activity

**Comment by MOYFbeta** [comment]
[Uploading test.zip…]()

**Comment by MOYFbeta** [comment]
源码龟速上传中

**Comment by MOYFbeta** [comment]
[test.zip](https://github.com/soft-summer-2021/summer2021/files/7026491/test.zip)
补充一下上传失败的源代码

**Comment by MOYFbeta** [comment]
大致定位到应该是AnotherActivity里面传给Textview的id不对

**Comment by MOYFbeta** [comment]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference

**Comment by MOYFbeta** [comment]
最近的更新：
给activity_another加了个id
`    <TextView
        android:id="@+id/text"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="#dddddd"
        android:textColor="@color/black"
        android:textSize="20sp"
        android:text="null"
        >
    </TextView>`

并且把AnotherActivity找id的语句改成了textView = findViewById(R.id.text);

然并卵

如果把
`TextView textView;
        textView = findViewById(R.id.text);
        textView.setText(message);`
注释掉，可以打开第二个窗口，（只不过不显示文字）
我猜findViewById(R.id.text);给我传回来一个null，但上网查好像写法没问题

**Comment by hzy1721** [comment]
`activity_another.xml`

```xml
<TextView
    android:id="@+id/another_text"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:background="#dddddd"
    android:textColor="@color/black"
    android:textSize="20sp"
    >
</TextView>
```

`AnotherActivity.java`

```java
@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_another);

    Intent intent = getIntent();
    String msg = intent.getStringExtra(MainActivity.EXTRA_MESSAGE);
    TextView textView = findViewById(R.id.another_text);
    textView.setText(msg);
}
```

原来的错误有 3 个：
- AnotherActivity 里你要赋值的那个 TextView 没有加 id
- findViewById 写成了 MainActivity 里的那个 EditText
- 在 setContentView 之前使用 findViewById

**Comment by KarryBanana** [comment]
似乎是你的editTextPersonName放错位置了

你是在anotherActivity下寻找这个textView，但实际上叫这个id的textView在MainActivity里面

main_activity.xml
```xml
<EditText
        android:id="@+id/editTextTextPersonName"
        android:background="#559988"
        android:textColor="#ffffff"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:ems="10"
        android:inputType="textPersonName"
        android:text="@string/edit_msg"
        android:importantForAutofill="no" />
```


你引用的是这个textView是在AnotherActivity下
AnotherActivity.java
```java
public class AnotherActivity extends AppCompatActivity implements Serializable {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Intent intent = getIntent();
        String msg = intent.getStringExtra(MainActivity.EXTRA_MESSAGE);

        TextView textView = findViewById(R.id.editTextTextPersonName);
        textView.setText(msg);

        setContentView(R.layout.activity_another);
    }
}
```

**Comment by MOYFbeta** [comment]
欧了
