### ISSUE TITLE
Java Swing 组件设置为不可更改

### ISSUE THREAD

**Issue by Rnkind** [soft-summer-2021/summer2021#60]
如题，需求是在这个窗口中，先点击顶部的开关才可以使得下方组件的可以被用户编辑
想要实现的效果大概如下图
![KUMHFW8G{P$EN_TZM96T 17](https://user-images.githubusercontent.com/89282985/130988414-213ae826-306d-4ab6-b565-0f9b49cc6fa9.png)
（在没有任何动作时，下方的Finish和Next均不可触发事件
![$@875%%~N 11~JYIZ(N5L9Y](https://user-images.githubusercontent.com/89282985/130988415-6d22f50e-b864-434c-81c0-7353e0d54e6a.png)
（选择某个文件后Next才可触发

请问助教如何组件的成员方法里面有没有这样的成员函数可以实现功能？
（需要点击开关才可设置的组件有按钮和文本框）

**Comment by huyikun** [comment]
不是很熟悉 Java Swing 组件，但选择文件必定会绑定在某个变量上，根据该变量是否为null对next按钮的disable属性进行设置应该就可以了吧
