### ISSUE TITLE
C++运行出现访问冲突

### ISSUE THREAD

**Issue by ZhMX1** [soft-summer-2021/summer2021#61]
运行程序的时候发生数组访问冲突
本身这个地方一开始运行的时候是好的，但是 后来又写了 一个函数再运行的时候就不能用了
![image](https://user-images.githubusercontent.com/89237121/130988970-a17d0eb8-498b-4082-8d10-2e659b221f23.png)
这个函数的功能是插入一个背景色透明的图片，调用的别人的函数，以确定没有在全局或者别的地方命名过一样的变量

**Comment by hzy1721** [comment]
访问冲突一般是数组越界或空指针引用，检查一下这个 `dstX` 是不是越界了。

**Comment by ZhMX1** [comment]
已经解决，是别的数组溢出但是在这里报错了
