### ISSUE TITLE
openCV如何以多个坐标点为顶点截图

### ISSUE THREAD

**Issue by WhySoHardToGiveName** [soft-summer-2021/summer2021#62]
![image](https://user-images.githubusercontent.com/89514061/131057504-09007b96-0c0b-4440-9490-9ae97a84fb9c.png)
得到人脸中关键点的坐标值，怎么只把五官截取出来？

**Comment by hzy1721** [comment]
```python
# 首尾相连关键点的坐标
poly_pts = np.array([poly_pts])
# 全黑的 mask
mask = np.zeros(img.shape[:2], np.uint8)
# 画出人脸轮廓线
cv2.polylines(mask, poly_pts, True, 255)
# 填充 mask 中人脸部分为全白 255
cv2.fillPoly(mask, poly_pts, 255)
# 将 img 中除人脸部分置 0，人脸部分不变
face_dark_bg = cv2.bitwise_and(img, img, mask=mask)
# 全白的背景
white_bg = np.ones_like(img, np.uint8) * 255
# 把人脸部分的背景取反，变成全 0
cv2.bitwise_not(white_bg, white_bg, mask=mask)
# 相加后的结果：背景还是 255 全白，人脸部分是 img 中人脸部分的像素值
face_white_bg = white_bg + face_dark_bg
```

![girl_201](https://user-images.githubusercontent.com/48407687/131058470-135989ee-8011-42d4-9368-b10298a5f632.jpg)

![girl_face_final](https://user-images.githubusercontent.com/48407687/131058484-0c385d80-88f8-4b83-863f-8248a5ad58e3.jpg)

我这里选的点跟你图里画的不一样，可以自己改一下。
