### ISSUE TITLE
在Java中，可否使用(Message) Object 来将一个Object类强制转换成Message类？

### ISSUE THREAD

**Issue by MOYFbeta** [soft-summer-2021/summer2021#63]
我之前的方法从服务器OutputStream读字符串，然后发给游戏逻辑解析，非常麻烦。后来发现可以在Message上附加Bundle非常方便地收发信息，于是重构了代码，但在使用Socket收发信息时遇到了问题

我试图从服务器的OutputStream里面读一个Message交给gameRunningData的readInfo，下面的方法是我查了各种资料拼凑成的方法，这样是否可行？
![image](https://user-images.githubusercontent.com/89012028/131073834-a2a5085f-b82f-4198-ac43-a0692b17a011.png)

**Comment by MOYFbeta** [comment]
核心问题是我能不能给Object做强制类型转换
![image](https://user-images.githubusercontent.com/89012028/131074410-f7555ae4-65bd-457b-a805-abf13aa381b1.png)

**Comment by hzy1721** [comment]
如果 newMsg 确实是 Message 对象，就没问题，否则抛异常。

相关知识可以搜索 “Java 下转型”。

**Comment by MOYFbeta** [comment]
好的，我试试
