### ISSUE TITLE
pyinstaller多个py文件打包spec SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by ycp8023** [soft-summer-2021/summer2021#64]
![image](https://user-images.githubusercontent.com/79349653/131074829-8204a9ca-b83f-438d-aa1b-1a29a5366869.png)

我是根据 https://blog.csdn.net/lghello/article/details/105824057 这个上面做的 只在spec的第一个列表里加了所有的文件路径

**Comment by dyn1721** [comment]
多试试别的博客？还可参考 #56  里面总结的可能出错情况
