### ISSUE TITLE
在pygame中如何使得一个函数在某一段时间内执行，在某一段时间内不执行

### ISSUE THREAD

**Issue by Mr-alsocrazy** [soft-summer-2021/summer2021#67]

**Comment by hzy1721** [comment]
什么意思？比如上午 8 点到中午 12 点执行函数 A，剩下时间不执行？

**Comment by Ten-Mao** [comment]
用time.perf_counter()先读取开始时间，再在游戏主体的while循环里定义另一个变量再次用time.perf_counter()记录时间，然后把想要在特定时间间隔内执行的程序用一个if条件判断两个时间的差在不在所需去区间里，如果在进入if语句执行目的代码
