### ISSUE TITLE
pygame设置一个按钮以后，怎样通过点击按钮弹出一个独立的对话框

### ISSUE THREAD

**Issue by Ten-Mao** [soft-summer-2021/summer2021#68]

**Comment by hzy1721** [comment]
pygame 没有提供对话框的 API，因为这不是一个游戏库需要提供的，对话框在工具软件用的比较多。

可以把 pygame 游戏嵌入到 tkinter 应用中，然后用 tkinter 的 API 弹出对话框，但是比较麻烦。

[https://stackoverflow.com/questions/23319059/embedding-a-pygame-window-into-a-tkinter-or-wxpython-frame](https://stackoverflow.com/questions/23319059/embedding-a-pygame-window-into-a-tkinter-or-wxpython-frame)

如果是与游戏内容相关的对话框，也可以自己绘制一个对话框，更符合游戏风格，类似于下面这个：

<img width="1389" alt="截屏2021-08-27 下午8 50 28" src="https://user-images.githubusercontent.com/48407687/131130006-016b1644-f744-4ad5-b0a0-9d129735e7c4.png">

有一个库叫做 [pygame-menu](https://pygame-menu.readthedocs.io/en/4.1.4/) 可以帮助完成类似的工作。

**Comment by dyn1721** [comment]
> pygame 没有提供对话框的 API，因为这不是一个游戏库需要提供的，对话框在工具软件用的比较多。
> 
> 可以把 pygame 游戏嵌入到 tkinter 应用中，然后用 tkinter 的 API 弹出对话框，但是比较麻烦。
> 
> https://stackoverflow.com/questions/23319059/embedding-a-pygame-window-into-a-tkinter-or-wxpython-frame
> 
> 如果是与游戏内容相关的对话框，也可以自己绘制一个对话框，更符合游戏风格，类似于下面这个：
> 
> <img alt="截屏2021-08-27 下午8 50 28" width="1389" src="https://user-images.githubusercontent.com/48407687/131130006-016b1644-f744-4ad5-b0a0-9d129735e7c4.png">
> 
> 有一个库叫做 [pygame-menu](https://pygame-menu.readthedocs.io/en/4.1.4/) 可以帮助完成类似的工作。

鬼泣5好评！
