### ISSUE TITLE
将python文件转为exe后，exe文件执行错误

### ISSUE THREAD

**Issue by wlfeng0509** [soft-summer-2021/summer2021#7]
![QQ图片20210822104636](https://user-images.githubusercontent.com/89327504/130340359-da74aa37-a2fa-49e0-8a55-6efba992aa03.png)

**Comment by wlfeng0509** [comment]
这是错误是怎么产生的呢

**Comment by hzy1721** [comment]
可以看一下[这篇文章](https://blog.csdn.net/u012252959/article/details/88868522)或者搜索其他文章。

顺便说一句：Python 项目可以不打包，源代码就可以跨平台执行，只需要在 README.md 里说明执行方法。而且源代码体积小，打包后体积反而会比较大。也最好写一个 `requirements.txt`，说明需要安装的包。

**Comment by wlfeng0509** [comment]
> 可以看一下[这篇文章](https://blog.csdn.net/u012252959/article/details/88868522)或者搜索其他文章。
> 
> 顺便说一句：Python 项目可以不打包，源代码就可以跨平台执行，只需要在 README.md 里说明执行方法。而且源代码体积小，打包后体积反而会比较大。也最好写一个 `requirements.txt`，说明需要安装的包。

好的，谢谢
