### ISSUE TITLE
为什么执行easyX会卡死

### ISSUE THREAD

**Issue by XXXXXXXXXXXJ** [soft-summer-2021/summer2021#70]
下载完VC2010和easyX，成功运行了easyX的示例代码
之后在完成自己代码的框架后执行代码就白屏了，再次运行easyX示例代码也白屏

**Comment by dyn1721** [comment]
> 再次运行easyX示例代码也白屏

是不是运行错文件了

断点调试 或者 print控制台输出下 ？ 还找不到问题发下完整代码

**Comment by XXXXXXXXXXXJ** [comment]
完整代码就easyX官网上的示例代码，第一次能成功画圆，第二次就白屏了。

**Comment by dyn1721** [comment]
> 完整代码就easyX官网上的示例代码，第一次能成功画圆，第二次就白屏了。

重建个项目再试试？ 这问题有点离谱

**Comment by XXXXXXXXXXXJ** [comment]
刚刚又试了下，白屏之后等了很久，运行成功了。
