### ISSUE TITLE
EasyX函数中部分putimage无法正常运行

### ISSUE THREAD

**Issue by nevergyt** [soft-summer-2021/summer2021#71]
![屏幕截图 2021-08-28 101939](https://user-images.githubusercontent.com/89232835/131203189-b4bec1aa-8bdd-4b8b-85ea-b6510019aeec.png)
![屏幕截图 2021-08-28 102000](https://user-images.githubusercontent.com/89232835/131203191-eb00a66e-4a79-4555-9287-c96ffe4a2dba.png)
屏幕中dead函数中putimage无法正常运行，只有声音，图画还是之前的图画

**Comment by jongjyh** [comment]
可以先检查下图片的路径是否正确，试试绝对路径，可执行文件是在debug之下的

**Comment by dyn1721** [comment]
或者别的绘制函数把这个覆盖了？

**Comment by nevergyt** [comment]
是在一个目录之下，而且如果没有点击鼠标是没有其他绘制函数的。
可是它不显示，还是上一个函数的画面

**Comment by dyn1721** [comment]
还没解决的话 把整个项目文件发一下 我本地跑跑看

**Comment by nevergyt** [comment]
[雷霆战机.zip](https://github.com/soft-summer-2021/summer2021/files/7070091/default.zip)

**Comment by dyn1721** [comment]
这问题还真是隐蔽。。
你dead函数里面绘制结束界面完了后，又重新开始新的关卡选择等界面，准备下一轮游戏。
但是你忘记了dead函数绘制还是在**批量绘制里面**，所以必须等到EndBatchDraw()执行才会开始真正的绘制。
![image](https://user-images.githubusercontent.com/49605687/131207690-3cd703bd-7350-484a-8374-caacb3a3e942.png)
所以会黑屏卡住
