### ISSUE TITLE
pygame中如何解决没有按预期点击到设置的按钮的位置上就会闪退的问题

### ISSUE THREAD

**Issue by uniqueeer** [soft-summer-2021/summer2021#72]
助教好，想问下在一开始选择模式的时候会出现没有点到按钮的位置上就会闪退要怎么解决呀，可以设置成点击其他的位置程序没有反应吗？

**Comment by dyn1721** [comment]
啊 这肯定是你那部分代码运行时报错了才会闪退   仔细排查调试下？

**Comment by uniqueeer** [comment]
嗯嗯写的时候只写了如果点击了按钮之后要做什么，没有写点击其他位置要怎么办。
我现在想用pygame.event.set_allowed()只让点击按钮的操作进入队列，但是用pygame.event.Event()自己定义事件的时候不知道怎么设置鼠标点击的位置（应该是一个范围

**Comment by uniqueeer** [comment]
这是写难度选择部分的代码，辛苦助教了
https://paste.ubuntu.com/p/fCjYhMFNJp/

**Comment by dyn1721** [comment]
这个问题应该不难发现吧 
你下图13行那个循环就是判断点击选择难度的结果 通过**flag_level**指示器跳出循环
但是你这么写就成了只要鼠标点击了，不管是不是真的改变了难度，**flag_level都会变成1** 然后跳出循环  
这就导致点到按钮以外的情况也认为选择好难度了，继续向下执行，此时**status.game_level不是你预设的（1,2,3）中的一个**  
估计后面哪步就出错了
![image](https://user-images.githubusercontent.com/49605687/131207938-98b5f695-e642-4031-a541-a31e794d5aa0.png)

**Comment by dyn1721** [comment]
你可以修改一下while循环条件，只有难度那个变量变成1 2 3中一个才跳出循环

**Comment by uniqueeer** [comment]
好嘞好嘞， 谢谢助教
