### ISSUE TITLE
JScrollPane重新渲染后滚动条消失

### ISSUE THREAD

**Issue by Rnkind** [soft-summer-2021/summer2021#74]
程序里的图形是用paint(Graphics g) 的方法画的，每次画好后用窗格调用setViewportView（）将图形加到滚动窗格中，现在才发现这么做以后窗格的滚动条就消失了，再画倒是也能渲染出来，但完全无法移动了，请问助教怎么改渲染的方法或者是保留滚动条？

**Comment by KarryBanana** [comment]
再次绘图的时候需要调用`setPreferredSize()`并对UI进行更新
可以参考下这篇博客修改下代码 [如何正确绘图和出现滚动条](https://blog.csdn.net/cankykong1/article/details/12686125)
