### ISSUE TITLE
EasyX图形库中鼠标点击问题

### ISSUE THREAD

**Issue by nevergyt** [soft-summer-2021/summer2021#75]
[雷霆战机.zip](https://github.com/soft-summer-2021/summer2021/files/7070392/default.zip)
![屏幕截图 2021-08-28 163730](https://user-images.githubusercontent.com/89232835/131211877-fc58c127-da6f-4670-85a5-6c55842cc78a.png)
if函数其中只有第二个生效，其他的按钮点击无反应

**Comment by dyn1721** [comment]
。。这种问题还是自己解决吧

**Comment by nevergyt** [comment]
主要是之前可以运行，我加上最后一个else if后第一个无法运行了，注释掉第三个也运行不了

**Comment by dyn1721** [comment]
这种问题还是真的自己**仔细多看几眼** 自己解决吧
![{EAK4 5$8L{NB}4DBN{~H{K](https://user-images.githubusercontent.com/49605687/131213608-334082fa-09e4-43f5-8718-0659ef9cc20f.png)
注意你的t数组长度是5 下标最多取到4 但是你取到**t[5]**了  
溢出直接**污染**了紧挨着定义的**flag变量**
![KAYB2H{(RRL0OC5T H~9SWL](https://user-images.githubusercontent.com/49605687/131213641-1c0a3e19-39c2-431a-9573-51d265cb39c5.png)

其实这种错误**哪怕当时没看到，编译器也是有提示的**
![JFK7FRIS54A T U(@$ VXZF](https://user-images.githubusercontent.com/49605687/131213662-361066b1-bce8-47f9-b77a-1c4ea5899b8d.png)

再不济 一定要学会**断点调试**，自己调试就会发现flag走完这步**直接从1变到了两千多万**  

现在能体会到**数组越界**的可怕了吧

**这种问题真的真的真的自己要学会排查，后面的课程可没有助教有时间有耐心给你们de这种bug**
