### ISSUE TITLE
pyinstaller打包pygame文件时，报错：AttributeError: Module 'PyQt5' has no attribute '__version__'

### ISSUE THREAD

**Issue by dsyyyy233** [soft-summer-2021/summer2021#76]
这是打包过程中的报错信息：
![微信截图_20210829104801](https://user-images.githubusercontent.com/89233745/131236608-646a89cd-5d07-44b5-b693-6c1436fba92c.png)
另外想问下打包多个文件这样输入正确吗？：
![微信截图_20210829104826](https://user-images.githubusercontent.com/89233745/131236627-f0db9adb-b1cf-4edc-9387-7a49f14050c6.png)

**Comment by hzy1721** [comment]
[https://stackoverflow.com/questions/67884654/attributeerror-module-pyqt5-has-no-attribute-version](https://stackoverflow.com/questions/67884654/attributeerror-module-pyqt5-has-no-attribute-version)

**Comment by dsyyyy233** [comment]
问题已解决，谢谢助教！
