### ISSUE TITLE
Android Studio在模拟器上运行app时一打开就闪退怎么解决

### ISSUE THREAD

**Issue by VeraMayLin** [soft-summer-2021/summer2021#77]
尝试运行app但是打开就闪退，代码也没有报错，应该怎么处理
![image](https://user-images.githubusercontent.com/82801068/131239095-788be4b8-de43-4fa9-81ae-da3365259429.png)

**Comment by hzy1721** [comment]
发一下项目文件？我帮你运行一下

**Comment by VeraMayLin** [comment]
[Uploading TimeSliceTest 2.zip…]()

**Comment by hzy1721** [comment]
> Uploading TimeSliceTest 2.zip…

没上传成功，用北航网盘吧。

**Comment by VeraMayLin** [comment]
https://bhpan.buaa.edu.cn:443/link/798BF34C3BBA5FC0C2653026A370375E
有效期限：2021-09-27 23:59

**Comment by hzy1721** [comment]
<img width="1440" alt="截屏2021-08-29 下午3 20 12" src="https://user-images.githubusercontent.com/48407687/131242169-dcce984b-a12b-4f0a-a5ee-dec43f322439.png">

AS 底部的 “Run” 部分可以查看调试信息，如果 APP 崩溃了 (闪退)，能看到是什么异常。

闪退是因为 `Schedule.java` 里的 SQL 语句执行错误，有两个错误：

1. `isImportant` 和 `isUrgent` 没有初始化
```java
// 修改前
public static String isImportant;
public static String isUrgent;

// 修改后
public static String isImportant = "isImportant";
public static String isUrgent = "isUrgent";
```
2. SQL 语句末尾多加了一个逗号
```java
// 修改前
@Override
public void onCreate(SQLiteDatabase db) {
    String sql = "CREATE TABLE "
            + Schedule.tableName
            + " (  "
            + "_id integer primary key autoincrement, "
            + Schedule.ScheduleText_1 + " TEXT, "
            + Schedule.isImportant + " integer, "
            + Schedule.isUrgent + " integer, "
            + Schedule.beginTime + " DATETIME, "
            + Schedule.ddl + " DATETIME, "  // 这里多加了一个逗号
            + ");";
    db.execSQL(sql);
}

// 修改后
@Override
public void onCreate(SQLiteDatabase db) {
    String sql = "CREATE TABLE "
            + Schedule.tableName
            + " (  "
            + "_id integer primary key autoincrement, "
            + Schedule.ScheduleText_1 + " TEXT, "
            + Schedule.isImportant + " integer, "
            + Schedule.isUrgent + " integer, "
            + Schedule.beginTime + " DATETIME, "
            + Schedule.ddl + " DATETIME "
            + ");";
    db.execSQL(sql);
}
```

**Comment by VeraMayLin** [comment]
修改之后闪退问题仍然存在
![image](https://user-images.githubusercontent.com/82801068/131242965-f880f81e-c3e8-46a6-85fa-78bdc285f6c2.png)

**Comment by hzy1721** [comment]
执行什么操作后闪退的？我这里可以正常打开。

<img width="429" alt="截屏2021-08-29 下午3 59 14" src="https://user-images.githubusercontent.com/48407687/131243192-27e891c8-ce2c-4321-968c-42a3d21d6de5.png">

根据你发的图片，是常见的空指针异常，调用 `setText` 的变量是空的。

**Comment by VeraMayLin** [comment]
尝试打开模拟器运行就会直接闪退
