### ISSUE TITLE
WPF可执行文件如何生成

### ISSUE THREAD

**Issue by wxy4869** [soft-summer-2021/summer2021#79]
WPF，在NuGet下载了Costura.Fody，然后重新生成解决方案。但是还有三个东西必须存在，exe才能运行
那三个东西是一个数据库文件history.db，这个东西是虽然删了exe也能运行，但是每次运行exe的时候他会自动出现
两个我不知道是什么东西的文件夹：x64\SQLite.Interop.dll和x64\SQLite.Interop.dll，这两个东西我在Visual Studio的解决方案资源管理器里找不到（我的System.Data.SQLite也是通过NuGet添加的，我不知道x64和x86这两个文件夹里的东西是怎么来的）

**Comment by dyn1721** [comment]
sry 助教们都不太熟悉WPF
