### ISSUE TITLE
c++使用msiSendString无法播放相应音乐文件

### ISSUE THREAD

**Issue by oldGreenIsMe** [soft-summer-2021/summer2021#8]
```cpp
#include <graphics.h>
#include <conio.h>
#include <mmsystem.h>
#pragma comment (lib,"Winmm.lib")
#define WIDTH 640
#define HEIGHT 480
void startUp()
{
	initgraph(WIDTH, HEIGHT);
	
	mciSendString("open F:\\visual studio程序文件\\程序设计实践大作业\\TankBattle\\808477084.mp3 alias bgm", NULL, 0, NULL);
	mciSendString("play bgm repeat", NULL, 0, NULL);
	_getch();
}
int main(void)
{
	startUp();
	return 0;
}
```

如题，已将字符集改为多字节字符集

**Comment by huyikun** [comment]
有报错信息吗
可参考一下这个： http://cn.voidcc.com/question/p-dkflulxu-ck.html
或者把mp3文件绝对路径改成相对路径试试

**Comment by oldGreenIsMe** [comment]
> 有报错信息吗

如果将字符集不改为多字节字符集就有报错，是那种无法编译的错误，改成相对路径也不行

错误(活动)	E0167	"const char *" 类型的实参与 "LPCWSTR" 类型的形参不兼容	TankBattle	F:\visual studio程序文件\程序设计实践大作业\TankBattle\源.cpp	13	

错误	C2664	“MCIERROR mciSendStringW(LPCWSTR,LPWSTR,UINT,HWND)”: 无法将参数 1 从“const char [29]”转换为“LPCWSTR”	TankBattle	F:\visual studio程序文件\程序设计实践大作业\TankBattle\源.cpp	12

**Comment by huyikun** [comment]
> > 有报错信息吗
> 
> 如果将字符集不改为多字节字符集就有报错，是那种无法编译的错误，改成相对路径也不行
> 
> 错误(活动) E0167 "const char *" 类型的实参与 "LPCWSTR" 类型的形参不兼容 TankBattle F:\visual studio程序文件\程序设计实践大作业\TankBattle\源.cpp 13
> 
> 错误 C2664 “MCIERROR mciSendStringW(LPCWSTR,LPWSTR,UINT,HWND)”: 无法将参数 1 从“const char [29]”转换为“LPCWSTR” TankBattle F:\visual studio程序文件\程序设计实践大作业\TankBattle\源.cpp 12

试试使用 _T 宏定义 ，头文件 #include <tchar.h>
参考： https://zhidao.baidu.com/question/327887942.html

数据类型不匹配，可以看一下函数原型：https://docs.microsoft.com/zh-cn/previous-versions//dd757161(v=vs.85)

**Comment by oldGreenIsMe** [comment]
> > > 有报错信息吗
> > 
> > 
> > 如果将字符集不改为多字节字符集就有报错，是那种无法编译的错误，改成相对路径也不行
> > 错误(活动) E0167 "const char *" 类型的实参与 "LPCWSTR" 类型的形参不兼容 TankBattle F:\visual studio程序文件\程序设计实践大作业\TankBattle\源.cpp 13
> > 错误 C2664 “MCIERROR mciSendStringW(LPCWSTR,LPWSTR,UINT,HWND)”: 无法将参数 1 从“const char [29]”转换为“LPCWSTR” TankBattle F:\visual studio程序文件\程序设计实践大作业\TankBattle\源.cpp 12
> 
> 试试使用 _T 宏定义 ，头文件 #include <tchar.h>
> 参考： https://zhidao.baidu.com/question/327887942.html
> 
> 数据类型不匹配，可以看一下函数原型：https://docs.microsoft.com/zh-cn/previous-versions//dd757161(v=vs.85)

用了_T后好了，谢谢
