### ISSUE TITLE
在试图使用javabean创建Json对象时，androidstuduo认为我必须使用Map

### ISSUE THREAD

**Issue by MOYFbeta** [soft-summer-2021/summer2021#83]
在试图使用javabean创建Json对象时，androidstuduo认为我必须使用Map
![image](https://user-images.githubusercontent.com/89012028/131270811-6c0470ee-0796-4f66-92c6-4484b13ed703.png)

这里是MMessage
![image](https://user-images.githubusercontent.com/89012028/131270830-c0875c44-7974-4c16-b9e2-37058045eb98.png)

走在网上看到的方法中直接输入一个class是ok的，并且上网查并没有查到JSONObject()必须传入Map的信息

**Comment by KarryBanana** [comment]
私聊已解决
